In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [ ]:
df = pd.read_excel('C:/Users/efe44/Desktop/veri madenciliÄŸi proje/OnlineRetail.xlsx')

In [3]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB
None

In [4]:
df['StockCode'] = df['StockCode'].astype(str)
transactions = df.groupby('InvoiceNo')['StockCode'].apply(list)
transactions

InvoiceNo
536365     [85123A, 71053, 84406B, 84029G, 84029E, 22752,...
536366                                        [22633, 22632]
536367     [84879, 22745, 22748, 22749, 22310, 84969, 226...
536368                          [22960, 22913, 22912, 22914]
536369                                               [21756]
                                 ...
C581484                                              [23843]
C581490                                       [22178, 23144]
C581499                                                  [M]
C581568                                              [21258]
C581569                                       [84978, 20979]
Name: StockCode, Length: 25900, dtype: object

In [5]:
te = TransactionEncoder()
te_ary = te.fit(transactions).transform(transactions)
transaction_df = pd.DataFrame(te_ary, columns=te.columns_)
transaction_df

,10002,10080,10120,10123C,10123G,10124A,10124G,10125,10133,10134,...,M,PADS,POST,S,gift_0001_10,gift_0001_20,gift_0001_30,gift_0001_40,gift_0001_50,m
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25895,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25896,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25897,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
25898,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25899,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [19]:
frequent_items = apriori(transaction_df, min_support=0.01, use_colnames=True)
frequent_items

       support                       itemsets
0     0.020193                        (15036)
1     0.012587                      (15056BL)
2     0.017876                       (15056N)
3     0.011236                        (16237)
4     0.012510                        (20675)
...        ...                            ...
1082  0.010270         (23199, 85099B, 23203)
1083  0.011429         (23202, 85099B, 23203)
1084  0.010077   (20723, 20724, 20719, 22355)
1085  0.010386  (85099B, 22386, 21931, 22411)
1086  0.011699   (22697, 22698, 22699, 22423)

[1087 rows x 2 columns]

In [23]:
rules = association_rules(frequent_items, num_itemsets=1, metric="confidence", min_threshold=0.8)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(21086),(21094),0.016525,0.020347,0.013514,0.817757,40.189576,1.0,0.013177,5.375529,0.991503,0.578512,0.813972,0.740947
1,(22579),(22578),0.013243,0.019923,0.010888,0.822157,41.267205,1.0,0.010624,5.510926,0.988863,0.488735,0.818542,0.684335
2,(22698),(22697),0.030965,0.040811,0.024865,0.802993,19.675976,1.0,0.023601,4.868796,0.979507,0.530041,0.794610,0.706132
3,(23171),(23170),0.014903,0.017645,0.012432,0.834197,47.277242,1.0,0.012169,5.924830,0.993657,0.618042,0.831219,0.769396
4,(23172),(23170),0.012124,0.017645,0.010502,0.866242,49.093367,1.0,0.010288,7.344275,0.991653,0.545090,0.863840,0.730714
5,(23172),(23171),0.012124,0.014903,0.010888,0.898089,60.260387,1.0,0.010707,9.666260,0.995474,0.674641,0.896547,0.814330
6,(84596F),(84596B),0.016834,0.020193,0.013514,0.802752,39.753890,1.0,0.013174,4.967393,0.991537,0.574713,0.798687,0.735984
7,"(20723, 20719)",(20724),0.015753,0.040541,0.012664,0.803922,19.830065,1.0,0.012025,4.893243,0.964769,0.290265,0.795637,0.558151
8,"(22356, 20719)",(20724),0.015328,0.040541,0.012587,0.821159,20.255248,1.0,0.011965,5.364865,0.965428,0.290812,0.813602,0.565817
9,"(20723, 22355)",(20724),0.016139,0.040541,0.012973,0.803828,19.827751,1.0,0.012319,4.890903,0.965142,0.296820,0.795539,0.561914
10,"(20723, 22356)",(20724),0.014749,0.040541,0.012664,0.858639,21.179756,1.0,0.012066,6.787287,0.967048,0.297101,0.852666,0.585510
11,"(22356, 22355)",(20724),0.016023,0.040541,0.012819,0.800000,19.733333,1.0,0.012169,4.797297,0.964783,0.293027,0.791549,0.558095
12,"(21086, 21080)",(21094),0.011429,0.020347,0.010232,0.895270,43.999051,1.0,0.009999,9.354101,0.988570,0.474910,0.893095,0.699058
13,"(21928, 22386)",(85099B),0.014826,0.082432,0.012355,0.833333,10.109290,1.0,0.011133,5.505405,0.914642,0.145521,0.818360,0.491608
14,"(22386, 21931)",(85099B),0.020000,0.082432,0.016062,0.803089,9.742389,1.0,0.014413,4.659804,0.915669,0.185963,0.785399,0.498968
15,"(22386, 22411)",(85099B),0.018224,0.082432,0.014672,0.805085,9.766602,1.0,0.013170,4.707521,0.914272,0.170633,0.787574,0.491535
16,"(22386, 85099F)",(85099B),0.013475,0.082432,0.010811,0.802292,9.732726,1.0,0.009700,4.641030,0.909509,0.127042,0.784531,0.466720
17,"(22386, DOT)",(85099B),0.013320,0.082432,0.010695,0.802899,9.740081,1.0,0.009597,4.655306,0.909446,0.125738,0.785191,0.466320
18,"(22698, 22423)",(22697),0.015521,0.040811,0.013359,0.860697,21.089915,1.0,0.012726,6.885608,0.967602,0.310872,0.854770,0.594019
19,"(22698, 22423)",(22699),0.015521,0.043243,0.013012,0.838308,19.385883,1.0,0.012340,5.917173,0.963369,0.284388,0.831000,0.569601
20,"(22697, 22698)",(22699),0.024865,0.043243,0.021197,0.852484,19.713703,1.0,0.020122,6.485804,0.973479,0.451852,0.845817,0.671332
21,"(22698, 22699)",(22697),0.023707,0.040811,0.021197,0.894137,21.909313,1.0,0.020229,9.060649,0.977531,0.489305,0.889633,0.706766
22,"(20723, 22355, 20719)",(20724),0.011737,0.040541,0.010077,0.858553,21.177632,1.0,0.009601,6.783155,0.964096,0.238792,0.852576,0.553562
23,"(22386, 21931, 22411)",(85099B),0.011969,0.082432,0.010386,0.867742,10.526705,1.0,0.009399,6.937706,0.915967,0.123621,0.855860,0.496869
24,"(22697, 22698, 22423)",(22699),0.013359,0.043243,0.011699,0.875723,20.251084,1.0,0.011121,7.698554,0.963491,0.260533,0.870105,0.573129
25,"(22698, 22699, 22423)",(22697),0.013012,0.040811,0.011699,0.899110,22.031167,1.0,0.011168,9.507258,0.967194,0.277727,0.894817,0.592885